### ISSUE TITLE
How to work your script zigag ??

### ISSUE THREAD

**Issue by xxxHEKETOSxxx** [liraeng/zigzag#1]
Hello! I decided to try your script, but I can't figure out how it works??
On the 15 minute timeframe with a difference of 5 minutes, it shows different data..
Can you suggest how it works?

![22222](https://user-images.githubusercontent.com/121030602/208433581-c0a68bb5-6797-4b05-8c34-69f6f8567e45.jpg)

This is the first result

![3333](https://user-images.githubusercontent.com/121030602/208433756-708d0fea-dde4-4ace-9ea7-6c21c49d03dd.jpg)

This is the second result, made 5 minutes after the first

**Comment by liraeng** [comment]
Hi mate, hope you are great.. I added some docstrings in the 'main.py' to ease the basic usage. For your case specific above if at first you are using the indicator for an M15 and want to obtain the same results for M5 I suggest you to use _depth (indicator entry parameter) in the second case (for M5) 3 times higher (15 minutes / 5 minutes), in this way I believe you will achieve pretty similar results.

Anyway, please let me know if it really works for your case and thanks in advance for your issue :)

**Comment by xxxHEKETOSxxx** [comment]
Thanks for answering. I'm afraid you misunderstood. This is the same result (15m) made with a difference of 5 minutes.

**Comment by liraeng** [comment]
Great, I think I got it.. in this case the issue is in the filter of the minimal deviation, probably the the algorithm detected a reversal pivot in your last 5 minutes.

I did a minor change in the deviation filter in order to keep the last one reversal trend. Please see the main.py  >> line 151 to 159 if you need further adjusts, but I think for now your issue may be solved
